-- 코드를 입력하세요
SELECT A.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE * C.SALES) AS TOTAL_SALES
  FROM BOOK A INNER JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
              INNER JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
              # INNER JOIN (SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES FROM BOOK_SALES WHERE DATE_FORMAT(SALES_DATE, '%Y%m') = '202201' GROUP BY BOOK_ID) C ON A.BOOK_ID = C.BOOK_ID
 WHERE DATE_FORMAT(C.SALES_DATE, '%Y%m') = '202201'
GROUP BY A.AUTHOR_ID, A.CATEGORY
ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC


# SELECT  A.AUTHOR_ID, A.CATEGORY, A.PRICE, C.SALES
#   FROM BOOK A INNER JOIN AUTHOR B ON A.AUTHOR_ID = B.AUTHOR_ID
#               INNER JOIN BOOK_SALES C ON A.BOOK_ID = C.BOOK_ID
# GROUP BY A.AUTHOR_ID, A.CATEGORY
# ORDER BY A.AUTHOR_ID ASC, A.CATEGORY DESC


# SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES FROM BOOK_SALES GROUP BY BOOK_ID
# SELECT BOOK_ID, SALES FROM BOOK_SALES WHERE BOOK_ID = '1'