-- 코드를 입력하세요
SELECT b.CATEGORY, SUM(a.SALES) AS TOTAL_SALES
# , (SELECT SUM(SALES) FROM BOOK_SALES 
#                                             WHERE SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31') AS TOTAL_SALES
  FROM BOOK_SALES a INNER JOIN BOOK b on a.BOOK_ID = b.BOOK_ID
 # WHERE a.SALES_DATE BETWEEN '2022-01-01' AND '2022-01-31'
 WHERE a.SALES_DATE LIKE '2022-01%'
GROUP BY b.CATEGORY
ORDER BY b.CATEGORY ASC

